# Generated by Django 4.1.2 on 2022-12-12 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_seq",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="문제 번호",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "question_title",
                    models.CharField(max_length=150, verbose_name="문제 제목"),
                ),
                (
                    "question_level",
                    models.CharField(max_length=150, verbose_name="문제 레벨"),
                ),
                (
                    "question_lang",
                    models.CharField(max_length=150, verbose_name="문제 언어"),
                ),
                ("question_text", models.TextField(verbose_name="문제 내용")),
                ("question_code", models.TextField(verbose_name="문제 정답 코드")),
                (
                    "question_creator",
                    models.ForeignKey(
                        db_column="question_creator",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="question_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_info",
            },
        ),
        migrations.CreateModel(
            name="UserQuestionMap",
            fields=[
                (
                    "map_seq",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="문제 번호",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "question_start_time",
                    models.DateTimeField(null=True, verbose_name="문제 풀이 시작 시간"),
                ),
                (
                    "question_end_time",
                    models.DateTimeField(null=True, verbose_name="문제 풀이 종료 시간"),
                ),
                (
                    "question_submit_count",
                    models.IntegerField(default=0, verbose_name="문제 제출 카운팅"),
                ),
                (
                    "question_correct_yn",
                    models.CharField(max_length=2, verbose_name="문제 정답 여부"),
                ),
                (
                    "question_save_yn",
                    models.CharField(max_length=2, verbose_name="문제 저장 여부"),
                ),
                (
                    "question_rating",
                    models.IntegerField(null=True, verbose_name="문제 별점"),
                ),
                (
                    "question_seq",
                    models.ForeignKey(
                        db_column="question_seq",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_map",
                        to="question.question",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_map",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_question_map",
            },
        ),
        migrations.CreateModel(
            name="Testcase",
            fields=[
                (
                    "testcase_seq",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="테스트 케이스 번호",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("testcase_input", models.TextField(verbose_name="테스트 케이스 입력값")),
                ("testcase_output", models.TextField(verbose_name="테스트 케이스 출력값")),
                (
                    "testcase_open_yn",
                    models.CharField(max_length=2, verbose_name="테스트 케이스 공개 여부"),
                ),
                (
                    "question_seq",
                    models.ForeignKey(
                        db_column="question_seq",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_testcase",
                        to="question.question",
                    ),
                ),
            ],
            options={
                "db_table": "testcase_info",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="user_id",
            field=models.ManyToManyField(
                through="question.UserQuestionMap", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
