# Generated by Django 4.1.3 on 2022-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ManyToManyField(through='question.UserQuestionMap', to='main.user'),
        ),
    ]
