# Generated by Django 4.1.3 on 2022-12-09 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_remove_question_user_id_question_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_creator',
            field=models.ForeignKey(db_column='question_creator', db_constraint=False, default='test', on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
