# Generated by Django 4.1.2 on 2022-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_seq', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='게시판 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('board_title', models.CharField(max_length=150, verbose_name='게시판 제목')),
                ('board_view_count', models.IntegerField(verbose_name='게시판 조회수 카운팅')),
                ('borad_link', models.CharField(max_length=150, verbose_name='게시판 링크')),
                ('user_id', models.CharField(max_length=150, verbose_name='사용자(작성자) 아이디')),
            ],
            options={
                'db_table': 'board_info',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_seq', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='문제 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_title', models.CharField(max_length=150, verbose_name='문제 제목')),
                ('question_level', models.CharField(max_length=150, verbose_name='문제 레벨')),
                ('question_lang', models.CharField(max_length=150, verbose_name='문제 언어')),
                ('question_text', models.TextField(verbose_name='문제 내용')),
                ('question_code', models.TextField(verbose_name='문제 정답 코드')),
                ('user_id', models.CharField(max_length=150, verbose_name='사용자(작성자) 아이디')),
            ],
            options={
                'db_table': 'question_info',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('testcase_seq', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='테스트 케이스 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('testcase_input', models.TextField(verbose_name='테스트 케이스 입력값')),
                ('testcase_output', models.TextField(verbose_name='테스트 케이스 출력값')),
                ('testcase_open_yn', models.CharField(max_length=2, verbose_name='테스트 케이스 공개 여부')),
                ('question_seq', models.IntegerField(verbose_name='문제 번호')),
            ],
            options={
                'db_table': 'testcase_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('user_password', models.CharField(max_length=100, verbose_name='사용자 비밀번호')),
                ('user_nickname', models.CharField(max_length=100, verbose_name='사용자 별명')),
                ('user_level', models.IntegerField(default=0, verbose_name='사용자 레벨')),
                ('user_experience', models.IntegerField(default=0, verbose_name='사용자 경험치')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question_seq', models.IntegerField(default=0, verbose_name='문제 번호')),
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='사용자 아이디')),
                ('question_solve_time', models.DateTimeField(auto_now=True, verbose_name='문제 풀이 시간')),
                ('question_submit_count', models.IntegerField(default=0, verbose_name='문제 제출 카운팅')),
                ('question_correct_yn', models.CharField(max_length=2, verbose_name='문제 정답 여부')),
                ('question_save_yn', models.CharField(max_length=2, verbose_name='문제 저장 여부')),
                ('question_rating', models.IntegerField(null=True, verbose_name='문제 별점')),
            ],
            options={
                'db_table': 'user_question_map',
                'unique_together': {('question_seq', 'user_id')},
            },
        ),
    ]
