# Generated by Django 4.1.3 on 2022-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_managers_rename_user_id_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, null=True, verbose_name='사용자 별명'),
        ),
    ]
