# Generated by Django 4.1.3 on 2022-12-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board", old_name="borad_link", new_name="board_link",
        ),
    ]
