# Generated by Django 4.1.3 on 2022-12-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_rename_board_link_board_borad_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board", old_name="borad_link", new_name="board_link",
        ),
    ]
